<?php
/**
 * @file
 * Takes care of module's (un)installation and update tasks.
 */

/**
 * Rename date format and type from database.
 */
function hy_locale_update_7002(&$sandbox) {
  db_query("UPDATE {date_format_type} SET type = 'short_date_only' WHERE type = 'date_format_short_date_only'");
  db_query("UPDATE {date_formats} SET type = 'short_date_only' WHERE type = 'date_format_short_date_only'");
}
