<?php
/**
 * @file Takes care of installation/update/uninstallation operations.
 */

/**
 * Convert intro text field to textarea field, enable maxlength module.
 */
function hy_course_implementation_update_7018() {
  module_enable(array('maxlength'));

  db_update('field_config')
    ->fields(array('type' => 'text_long'))
    ->condition('field_name', 'field_field_imp_header_intro_tex')
    ->execute();

  // From text.install for long text fields
  $textarea_spec = array(
    'type' => 'text',
    'size' => 'big',
    'not null' => FALSE,
  );

  db_change_field('field_data_field_field_imp_header_intro_tex', 'field_field_imp_header_intro_tex_value', 'field_field_imp_header_intro_tex_value', $textarea_spec);
  db_change_field('field_revision_field_field_imp_header_intro_tex', 'field_field_imp_header_intro_tex_value', 'field_field_imp_header_intro_tex_value', $textarea_spec);
  field_cache_clear(TRUE);
}
