<?php
/**
 * @file
 * Code for the § open university feature.
 */

include_once 'uhc_open_university.features.inc';

/**
 * Implements hook_menu_block_blocks().
 */
function uhc_open_university_menu_block_blocks() {
  return array(
    'open-university-nav-level2' => array(
      'admin_title' => 'Open university navigation (level 2+)',
      'depth'       => 0,
      'expanded'    => TRUE,
      'follow'      => FALSE,
      'level'       => 1,
      'menu_name'   => 'menu-open-university-navigation',
      'parent_mlid' => 0,
      'sort'        => TRUE,
      'title_link'  => FALSE,
    ),
  );
}

/**
 * Implements hook_preprocess_block().
 *
 * Alter sitename when open uni context active
 */
function uhc_open_university_preprocess_block(&$vars) {
  $contexts = context_active_contexts();
  if (array_key_exists('open_university_header_and_footer', $contexts)) {
    if ($vars['block_html_id'] == 'block-hy-contact-hy-logo-block') {
      $vars['content'] = '<a href="http://www.helsinki.fi/university/">
        <svg width="53" height="50" class="site-logo">
            <image xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/profiles/uh_coursepages/themes/hy_doo/images/hy_logo_white.svg" src="/profiles/uh_coursepages/themes/hy_doo/images/ie/helsinki_university_53x50.png" width="53" height="50"></image>
        </svg>
        <h2 class="site-name">'. t("Open University") . '</h2></a>';
    }
  }
}

/**
 * Implements hook_block_info().
 */
function uhc_open_university_block_info() {
  $blocks = array();
  $blocks['uhc_open_university_contactblock'] = array(
    'info' => t('HY Open University Contact information'),
  );
  return $blocks;
}

/**
* Implements hook_block_view().
*/
function uhc_open_university_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'uhc_open_university_contactblock':

      // Specify current realm for fetching variables
      global $language;
      $realm = 'language';
      $realm_key = $language->language;
      $content = variable_store_get($realm, $realm_key, 'uhc_open_university_contactblock');

      $block['subject'] = '';
      $block['content'] = array('#markup' => $content['value'], '#format' => $content['format']);
      break;
  }

  return $block;
}

/**
 * Implements hook_context_plugins().
 */
function uhc_open_university_context_plugins() {
  $plugins = array();
  $plugins['uhc_open_university_is_open_university_section'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'uhc_open_university') .'/plugins',
      'file' => 'uhc_open_university_context_condition_open_university_section.inc',
      'class' => 'uhc_open_university_context_condition_open_university_section',
      'parent' => 'context_condition',
    ),
  );
  return $plugins;
}

/**
 * Implements hook_context_registry().
 */
function uhc_open_university_context_registry() {
  return array(
    'conditions' => array(
      'uhc_open_university_context_condition_open_university_section' => array(
        'title' => t('Open university section'),
        'plugin' => 'uhc_open_university_is_open_university_section',
      ),
    ),
  );
}

/**
 * Implements hook_node_view().
 */
function uhc_open_university_node_view($node, $view_mode, $langcode) {
  if ($plugin = context_get_plugin('condition', 'uhc_open_university_context_condition_open_university_section')) {
    $plugin->execute($node);
  }
}

/**
 * Implementation of hook_menu().
 */
function uhc_open_university_menu() {
  // Empty page callback for open-university, so that we may populate them with
  // blocks using context.
  $items['open-university'] = array(
    'page callback' => 'uhc_open_university_page',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Implementation of hook_page().
 */
function uhc_open_university_page() {
  return ' ';
}
