<?php
/**
 * @license GPL, or GNU General Public License, version 3
 * @license http://opensource.org/licenses/GPL-3.0
 * @see README.md how to contribute to this project
 */

/**
 * Implements hook_node_view().
 */
function uhc_elisa_chat_node_view($node, $view_mode, $langcode) {
  uhc_elisa_chat_add($node);
}

function uhc_elisa_chat_add($node) {
  if (uhc_elisa_chat_enabled($node)) {
    $js = drupal_get_path('module', 'uhc_elisa_chat') . '/js/elisa-chat.js';
    drupal_add_js($js, array('type' => 'file', 'scope' => 'header'));
  }
}

function uhc_elisa_chat_enabled($node) {
  $nids = variable_get('uhc_elisa_chat_nids', array());

  return in_array($node->nid, $nids);
}
