<?php
/**
 * @file
 * Code for the Navigation feature.
 *
 * @license GPL, or GNU General Public License, version 3
 * @license http://opensource.org/licenses/GPL-3.0
 * @see README.md how to contribute to this project
 */

include_once 'uhc_navigation.features.inc';

/**
 * Implements hook_menu_alter().
 *
 * We want to allow people administer menu links, but not menus.
 */
function uhc_navigation_menu_alter(&$items) {
  if (isset($items['admin/structure/menu/manage/%menu/edit'])) {
    $items['admin/structure/menu/manage/%menu/edit']['access callback'] = 'uhc_navigation_menu_manage_access';
  }
  if (isset($items['admin/structure/menu/manage/%menu/delete'])) {
    $items['admin/structure/menu/manage/%menu/delete']['access callback'] = 'uhc_navigation_menu_manage_access';
  }
}

/**
 * Callback function for determining whether user has access to manage the menu.
 */
function uhc_navigation_menu_manage_access($permission) {
  global $user;
  // If user is admin fallback to original access callback.
  $admin_rid = variable_get('admin_role', 0);
  if ($user->uid == 1 || ($admin_rid > 0 && user_has_role($admin_rid))) {
    return user_access($permission);
  }
  else {
    // In any other cases we deny no matter what.
    return FALSE;
  }
}
