<?php
/**
 * @file
 * Code for the Navigation feature.
 *
 * @license GPL, or GNU General Public License, version 3
 * @license http://opensource.org/licenses/GPL-3.0
 * @see README.md how to contribute to this project
 */

include_once 'uhc_navigation.features.inc';

/**
 * Implements hook_menu_alter().
 *
 * We want to allow people administer menu links, but not menus.
 */
function uhc_navigation_menu_alter(&$items) {
  if (isset($items['admin/structure/menu/manage/%menu/edit'])) {
    $items['admin/structure/menu/manage/%menu/edit']['access callback'] = 'uhc_navigation_menu_manage_access';
  }
  if (isset($items['admin/structure/menu/manage/%menu/delete'])) {
    $items['admin/structure/menu/manage/%menu/delete']['access callback'] = 'uhc_navigation_menu_manage_access';
  }
}

/**
 * Callback function for determining whether user has access to manage the menu.
 */
function uhc_navigation_menu_manage_access($permission) {
  global $user;
  // If user is admin fallback to original access callback.
  $admin_rid = variable_get('admin_role', 0);
  if ($user->uid == 1 || ($admin_rid > 0 && user_has_role($admin_rid))) {
    return user_access($permission);
  }
  else {
    // In any other cases we deny no matter what.
    return FALSE;
  }
}

/**
 * Implements hook_block_info_alter().
 */
function uhc_navigation_block_info_alter(&$blocks, $theme, $code_blocks) {
  // Set main-menu navigation title and class
  if (isset($blocks['menu']['og-menu-single'])) {
    $blocks['menu']['og-menu-single']['title'] = '<none>';
    $blocks['menu']['og-menu-single']['css_class'] = 'main-menu';
  }
}

/**
 * Implements template_preprocess_block().
 * Add javascript for main menus.
 */
function uhc_navigation_preprocess_block(&$variables) {
  $block = $variables['block'];
  $menus = array('open_university_menu_expanded', 'og-menu-single');
  if (in_array($block->delta, $menus)) {
    drupal_add_js(libraries_get_path('masonry') . '/dist/masonry.pkgd.min.js', array('scope' => 'footer'));
    drupal_add_js(libraries_get_path('matchmedia') . '/matchMedia.js', array('scope' => 'footer'));
    drupal_add_js(drupal_get_path('module', 'uhc_navigation') . '/js/menu.js', array('scope' => 'footer'));
    drupal_add_js(drupal_get_path('module', 'uhc_navigation') . '/js/mobile_menu.js', array('scope' => 'footer'));
  }
}
