<?php
/**
 * @file
 * Code for the UHC Dev feature feature.
 *
 * @license GPL, or GNU General Public License, version 3
 * @license http://opensource.org/licenses/GPL-3.0
 * @see README.md how to contribute to this project
 */

include_once 'uhc_dev_feature.features.inc';

/**
 * Implements hook_menu().
 */
function uhc_dev_feature_menu() {
  $items['test/course'] = array(
    'page callback' => '_uhc_dev_feature_integration_get_course',
    'delivery callback' => 'drupal_json_output',
    'access callback' => TRUE,
  );
  $items['test/implementation'] = array(
    'page callback' => '_uhc_dev_feature_integration_get_course_implementation',
    'delivery callback' => 'drupal_json_output',
    'access callback' => TRUE,
  );

  return $items;
}

function _uhc_dev_feature_integration_get_course($id) {
  $url = variable_get('uhc_course_source_item_url', '');
  $url = str_replace(':id', $id, $url);
  $url = PortalMigrationBase::prependHostIfMissing($url);
  return _uhc_dev_feature_return_json_response($url);
}

function _uhc_dev_feature_integration_get_course_implementation($id, $lang = 'fi') {
  $url = variable_get('uhc_course_implementation_source_item_url', '');
  $url = str_replace(':id', $id, $url);
  $url = str_replace(':lang', $lang, $url);
  $url = PortalMigrationBase::prependHostIfMissing($url);
  return _uhc_dev_feature_return_json_response($url);
}

function _uhc_dev_feature_return_json_response($url) {
  return drupal_json_decode(file_get_contents($url));
}