<?php
/**
 * @file
 * Code for the UHC Course feature.
 *
 * @license GPL, or GNU General Public License, version 3
 * @license http://opensource.org/licenses/GPL-3.0
 * @see README.md how to contribute to this project
 */

include_once 'uhc_course.features.inc';

function uhc_course_views_post_execute(&$view) {
  if($view->name == 'course_node_references') {
    drupal_add_js(drupal_get_path('module', 'uhc_course') . '/js/show_past_imps.js', array('scope' => 'footer'));
  }
}
