<?php
/**
 * @file
 * Code for the UHC statistics feature.
 *
 * @license GPL, or GNU General Public License, version 3
 * @license http://opensource.org/licenses/GPL-3.0
 * @see README.md how to contribute to this project
 */

include_once 'uhc_statistics.features.inc';

/**
 * Implements hook_menu().
 */
function uhc_statistics_menu() {
  $items['statistics'] = array(
    'page callback' => 'uhc_statistics_page',
    'access callback' => TRUE,
   	//'access callback' => 'uhc_statistics_access',
   	//'access arguments' => array(1, array('administrator', 'admin')),
  );
  return $items;
}

/**
 * Access callback for statistics, only for admin role
 */
function uhc_statistics_access($user, $roles = array()) {
  foreach ($roles as $role) {
    if (in_array($role, $user->roles)) {
      return TRUE;
    }
  }
  return FALSE; 
}

/**
 * Page callback for statistics
 */
function uhc_statistics_page() {
  return ' ';	
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Add date popup for timestamp exposed filter
 */
function uhc_statistics_form_views_exposed_form_alter(&$form, $form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-statistics-page-3') {
    drupal_add_css(drupal_get_path('module', 'uhc_statistics') . '/css/uhc_statistics.css', array('group' => CSS_THEME, 'type' => 'file'));
    foreach($form['timestamp'] as &$timestamp_element) {
      if (is_array($timestamp_element)) {
        $timestamp_element['#type'] = 'date_popup';
        $timestamp_element['#date_format'] = 'd.m.Y';
      }
    }
  }
}
