<?php
/**
 * @file
 * Contains module implementation of UHC Molecular Biosciences module.
 */

include_once 'uhc_molecular_biosciences.features.inc';

/**
 * Implementation of hook_menu().
 */
function uhc_molecular_biosciences_menu() {
  // Empty page callback for genetics, so that we may populate them with blocks
  // using context.
  $items['molecular-biosciences'] = array(
    'page callback' => 'uhc_molecular_biosciences_page',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Implementation of hook_page().
 */
function uhc_molecular_biosciences_page() {
  return ' ';
}
