<?php
/**
 * @file
 * Code for the UHC Feedback feature.
 */

include_once 'uhc_feedback.features.inc';
/**
 * @file
 * Customizations to feedback module.
 *
 * @license GPL, or GNU General Public License, version 3
 * @license http://opensource.org/licenses/GPL-3.0
 * @see README.md how to contribute to this project
 */

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add placeholder text to feedback form, Hide certain form elements.
 * Add JS for adding classes to form block. Replace default submit handler.
 */
function uhc_feedback_form_feedback_form_alter(&$form, &$form_state, $form_id) {

  foreach($form['#submit'] as &$submit_handler) {
    if ($submit_handler == 'feedback_form_submit') {
      $submit_handler = 'uhc_feedback_form_submit';
    }
  }

  $form['#attached']['js'][] = drupal_get_path('module', 'uhc_feedback') . '/js/uhc_feedback.js';
  $placeholder = t('Give feedback about the service...');
  $form['message']['#attributes']['placeholder'] = $placeholder;
  $form['message']['#attributes']['title'] = $placeholder;
  $form['is_open_university'] = array(
    '#type' => 'value',
    '#value' => uhc_open_university_is_open_university_context(),
  );
  unset($form['message']['#title']);
  unset($form['messages']);
  unset($form['help']);

  _uhc_feedback_add_response_email_default_value($form);
}

/**
 * Modified Form submission handler for feedback_form().
 * Message changed.
 */
function uhc_feedback_form_submit($form, &$form_state) {

  $entry = new stdClass();
  entity_form_submit_build_entity('feedback', $entry, $form, $form_state);
  $entry->message = $form_state['values']['message'];
  $entry->location = $form_state['values']['location'];
  $entry->is_open_university = (bool) $form_state['values']['is_open_university'];
  feedback_save($entry);

  drupal_set_message(t('Thank you'));
}

function _uhc_feedback_add_response_email_default_value(&$form) {
  if (user_is_logged_in() && isset($form['field_feedback_email'][LANGUAGE_NONE][0]['email'])) {
    global $user;
    $form['field_feedback_email'][LANGUAGE_NONE][0]['email']['#default_value'] = $user->mail;
  }
}

/**
 * Implements hook_views_api().
 */
function uhc_feedback_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_feedback_insert().
 */
function uhc_feedback_feedback_insert($entry) {
  if ($entry->is_open_university) {
    $to = variable_get('uhc_feedback_open_university_email', 'avoin-yleinen@helsinki.fi');
  }
  else {
    $to = variable_get('uhc_feedback_efecte_email', 'opetusteknologia@helsinki.fi');
  }
  uhc_feedback_email_to($entry, $to);
}

/**
 * Composes and sends the submitted feedback message to given email address.
 *
 * @param $entry object Feedback object.
 * @param $to string Email address
 */
function uhc_feedback_email_to($entry, $to) {
  $module = 'uhc_feedback';
  $key = 'feedback';
  global $language;
  $from = uhc_feedback_get_email($entry);

  $params = array(
    'subject' => variable_get('uhc_feedback_email_subject', 'Palaute kurssisivuilta'),
    'message' => uhc_feedback_build_email_body($entry),
    'return_path' => variable_get('site_mail', ''),
    'from' => $from
  );

  drupal_mail($module, $key, $to, $language, $params, $from);
}

function uhc_feedback_get_email($entry) {
  return uhc_feedback_response_expected($entry) && !empty($entry->field_feedback_email[LANGUAGE_NONE][0]['email'])
    ? $entry->field_feedback_email[LANGUAGE_NONE][0]['email']
    : variable_get('uhc_feedback_noreply_email', 'noreply@helsinki.fi');
}

function uhc_feedback_build_email_body($entry) {
  global $base_url;
  $url = !empty($entry->url) ? $entry->url : "$base_url/$entry->location";
  $time = date('d.m.Y H:i:s', $entry->timestamp);
  $user = $entry->uid > 0 ? user_load($entry->uid) : FALSE;
  $user_name = $user ? $user->name : t('Anonymous user');
  $user_email = uhc_feedback_get_email($entry);
  $message = check_plain($entry->message);
  $response_expected = uhc_feedback_response_expected($entry) ? t('I would like to get a response to my feedback') : FALSE;
  $meta = $entry->useragent;

  $body = array(
    $url,
    $time,
    $user_name,
    $message,
    $response_expected,
    $user_email,
    $meta
  );

  $body = array_filter($body, function ($entry) {
    return !empty($entry);
  });

  return implode("\n\n", $body);
}

function uhc_feedback_response_expected($entry) {
  return !empty($entry->field_feedback_respond[LANGUAGE_NONE][0]['value'])
    && $entry->field_feedback_respond[LANGUAGE_NONE][0]['value'];
}

/**
 * Implements hook_mail().
 */
function uhc_feedback_mail($key, &$message, $params) {
  if ($key == 'feedback') {
    $message['subject'] = $params['subject'];
    $message['body'][] = $params['message'];
    $message['headers']['Return-Path'] = $params['return_path'];
    $message['headers']['Sender'] = $params['from'];
  }
}

/**
 * Implements hook_page_alter().
 */
function uhc_feedback_page_alter(&$page) {
  $show_feedback_form = isset($page['page_bottom']['feedback'])
    && (uhc_open_university_is_open_university_context() || user_is_logged_in());

  if (!$show_feedback_form) {
    unset($page['page_bottom']['feedback']);
  }
}
