<?php
/**
 * @file
 * Code for the UHC Feedback feature.
 */

include_once 'uhc_feedback.features.inc';
/**
 * @file
 * Customizations to feedback module.
 *
 * @license GPL, or GNU General Public License, version 3
 * @license http://opensource.org/licenses/GPL-3.0
 * @see README.md how to contribute to this project
 */

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add placeholder text to feedback form, Hide certain form elements.
 * Add JS for adding classes to form block. Replace default submit handler.
 */
function uhc_feedback_form_feedback_form_alter(&$form, &$form_state, $form_id) {

  foreach($form['#submit'] as &$submit_handler) {
    if ($submit_handler == 'feedback_form_submit') {
      $submit_handler = 'uhc_feedback_form_submit';
    }
  }

  $form['#attached']['js'][] = drupal_get_path('module', 'uhc_feedback') . '/js/uhc_feedback.js';
  $form['message']['#attributes']['placeholder'] = t('Give feedback about the service...');
  unset($form['message']['#title']);
  unset($form['messages']);
  unset($form['help']);

  _uhc_feedback_add_response_email_default_value($form);
}

/**
 * Modified Form submission handler for feedback_form().
 * Message changed.
 */
function uhc_feedback_form_submit($form, &$form_state) {

  $entry = new stdClass();
  entity_form_submit_build_entity('feedback', $entry, $form, $form_state);
  $entry->message = $form_state['values']['message'];
  $entry->location = $form_state['values']['location'];
  feedback_save($entry);

  drupal_set_message(t('Thank you'));
}

function _uhc_feedback_add_response_email_default_value(&$form) {
  if (user_is_logged_in() && isset($form['field_feedback_email'][LANGUAGE_NONE][0]['email'])) {
    global $user;
    $form['field_feedback_email'][LANGUAGE_NONE][0]['email']['#default_value'] = $user->mail;
  }
}

/**
 * Implements hook_views_api().
 */
function uhc_feedback_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}
