<?php
/**
 * @file
 * Module's (un)installation tasks.
 *
 * @license GPL, or GNU General Public License, version 3
 * @license http://opensource.org/licenses/GPL-3.0
 * @see README.md how to contribute to this project
 */

/**
 * Implements hook_uninstall().
 */
function uhc_autofill_metadata_uninstall() {
  variable_del('uhc_enrollments_base_url');
  variable_del('uhc_refresh_enrollments');
  variable_del('uhc_autofill_metadata_override_enrollments');
}
