name = Helsingin Yliopisto Julkiset - Basic
description = Basic format for Helsingin yliopisto basic page.
preview = preview.png
template = hyj-basic-layout

; Regions
regions[top_bar_main]           = Top bar main
regions[top_bar_sub]            = Top bar sub
regions[menu_bar]               = Menu bar
regions[navigation]             = Navigation
regions[content_prefix]         = Content prefix
regions[content_sidebar_left]   = Content sidebar left
regions[content_sidebar_right]  = Content sidebar right
regions[content]                = Content
regions[content_suffix]         = Content suffix
regions[after_content]          = After content (unwrapped)
regions[action_footer]          = Action Footer
regions[info_footer]            = Info Footer
regions[footer]                 = Footer

; Stylesheets
stylesheets[all][] = css/layouts/hyj-basic/hyj-basic.layout.css
