<?php
/**
 * @file Installs/updates/uninstalls.
 */

/**
 * Implements hook_uninstall().
 * Formal uninstallation hook.
 */
function hy_search_portal_feature_uninstall() {
  variable_del('hy_search_portal_feature_host');
  variable_del('hy_search_portal_feature_port');
  variable_del('hy_search_portal_feature_path');
}

/**
 * Enable Facet API Bonus.
 */
function hy_search_portal_feature_update_7004() {
  module_enable(array('facetapi_bonus'));
}
