<?php
/**
 * @file
 * Code for the UHC Content Administration feature.
 *
 * @license GPL, or GNU General Public License, version 3
 * @license http://opensource.org/licenses/GPL-3.0
 * @see README.md how to contribute to this project
 */

/**
 * Implements hook_views_api().
 */
function uhc_content_administration_feature_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_preprocess_page().
 *
 * NON-FEATURE CODE: This implementation will hide tabs from node edit form from
 * editors, as they are considered as distraction.
 */
function uhc_content_administration_feature_preprocess_page(&$variables) {
  // When editing an node
  $arg = arg();
  $url_match = (count($arg) == 3 && $arg[0] == 'node' && $arg[2] == 'edit');
  $node_match = (isset($variables['node']->nid) && $variables['node']->type == 'course_implementation');
  if ($url_match && $node_match) {
    // And if we're in editor role
    global $user;
    $role = user_role_load_by_name('editor-in-chief of communications');
    foreach ($user->roles as $rid => $role_name) {
      if ($rid == $role->rid) {
        // Reduce distraction by removing tabs. Editor should have "Cancel"
        // button provided for navigating back. (see DOO-120).
        $variables['tabs']['#access'] = FALSE;
        break;
      }
    }
  }
}

/**
 * Implements hook_node_update().
 * @see _uhc_content_administration_feature_set_frontpage_if_requested()
 */
function uhc_content_administration_feature_node_update($node) {
  _uhc_content_administration_feature_set_frontpage_if_requested($node, 'portal_page');
}

/**
 * Implements hook_node_insert().
 * @see _uhc_content_administration_feature_set_frontpage_if_requested()
 */
function uhc_content_administration_feature_node_insert($node) {
  _uhc_content_administration_feature_set_frontpage_if_requested($node, 'portal_page');
}

/**
 * Helper function for checking whether node was checked to be promoted in front
 * page.
 *
 * When node type gets saved, we check whether the "Promote to frontpage" is
 * checked and then put the node as homepage.
 *
 * Node should be field translatable, so it should be translated and the
 * homepage should work in all languages.
 *
 * This was decided to be done in code instead of Rules, because Rules did not
 * support setting Drupal variables out of the box.
 *
 * @param $node
 * @param $node_type
 */
function _uhc_content_administration_feature_set_frontpage_if_requested($node, $node_type) {
  if ($node->type == $node_type && $node->promote == 1) {
    // When saving a node having "Promote to frontpage" checked
    if (isset($node->nid)) {

      // Then set this node as front page
      $entity_uri = entity_uri('node', $node);
      variable_set('site_frontpage', $entity_uri['path']);

      // And uncheck "Promote to front page" from other same type nodes
      $promoted_nodes = node_load_multiple(array(), array('type' => $node_type, 'promote' => 1));
      foreach ($promoted_nodes as &$promoted_node) {
        // Loop over each promoted node, and when it's not this node we're now
        // promoting, then just set promote to FALSE and save.
        if ($promoted_node->nid != $node->nid) {
          $promoted_node->promote = 0;
          node_save($promoted_node);
        }
      }

    }
  }
}

/**
 * Implements hook_form_alter().
 *
 * Attach an generic "actions" JS file which modifies some elements using jQuery
 * selectors. We want to do this instead when we find too tricky to alter some
 * complex elements.
 */
function uhc_content_administration_feature_form_alter(&$form, &$form_state) {
  $form['#attached']['js'][] = drupal_get_path('module', 'uhc_content_administration_feature') . '/js/content-admin-actions.js';
}
