<?php
/**
 * @file
 * Code for the uhc_search_front_page feature.
 */

include_once 'uhc_search_front_page.features.inc';

/**
 * Implements hook_form_alter().
 */
function uhc_search_front_page_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-uhc-portal-search-front-page--desktop') {
    $form['search']['#attributes']['placeholder'] = t('The name or code of the course');
  }
}

/**
 * Implements hook_block_view_alter().
 */
function uhc_search_front_page_block_view_alter(&$data, $block) {
  if ($block->bid == 'views-0580398bf6a2f9d60b32760e9900b13c') {
	$block->css_class = 'ds-grid-8 ';
    $data['content']['#suffix'] = '
      <div class="messages search-info ds-grid-8"><p>' . t('Students are advised to access their active courses via My Studies') . '<a href="https://student.helsinki.fi"></a></br>
      ' . t('Teachers are advised to access their active courses via My Teaching') . '<a href="https://teacher.helsinki.fi"></a></p></div>';
  }
}
