<?php
/**
 * @file
 * Contains module implementation of UHC Genetics module.
 */

include_once 'uhc_genetics.features.inc';

/**
 * Implementation of hook_menu().
 */
function uhc_genetics_menu() {
  // Empty page callback for genetics, so that we may populate them with blocks
  // using context.
  $items['genetics'] = array(
    'page callback' => 'uhc_genetics_page',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Implementation of hook_page().
 */
function uhc_genetics_page() {
  return ' ';
}
