<?php
/**
 * @file
 * Installation/update/uninstallation code for the uhc_ds feature.
 *
 * @license GPL, or GNU General Public License, version 3
 * @license http://opensource.org/licenses/GPL-3.0
 * @see README.md how to contribute to this project
 */

/**
 * Implements hook_uninstall().
 */
function uhc_ds_uninstall() {
  variable_del('uhc_ds_leiki_config');
}

/**
 * Enable UHC Course Hierarchy module.
 */
function uhc_ds_update_7001() {
  module_enable(array('uhc_course_hierarchy'));
}
